In [190]:
from bs4 import BeautifulSoup
import requests
url = BeautifulSoup("https://www.worldometers.info/coronavirus/","html.parser")
soup = requests.get(url)
soup

C:\Users\Acer\AppData\Local\Temp\ipykernel_12276\933022301.py:3: MarkupResemblesLocatorWarning:

The input looks more like a URL than markup. You may want to use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.

In [191]:
#soup.text

In [192]:
soup = BeautifulSoup(soup.text,"lxml") #converting to lxml
table_code = soup.table
table_code

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>131,612,000</td>
<td></td>
<td>1,692,250</td>
<td></td>
<td>127,135,297</td>
<td>+665</td>
<td>2,784,453</td>
<td>6,705</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>221,467,169</td>
<td>+120</td>
<td>1,553,255</td>
<td>+1</td>
<td>205,658,939</td>
<td>+398</td>
<td>14,254,975</td>
<td>14,733</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>253,232,601</td>
<td>+26</td>
<td>2,100,643</td>
<td></td>
<td>248,565,603</td>
<td>+904</td>
<td>2,566,355</td>
<td>4,510</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>69,859,756</td>
<td></td>
<td>1,365,807</td>
<td></td>
<td>66,650,237</td>
<td></td>
<td>1,843,712</td>
<td>8,953</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>14,844,285</td>
<td>+441</td>
<td>32,767</td>
<td></td>
<td>14,697,196</td>
<td></td>
<td>114,322</td>
<td>40</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,860,287</td>
<td></td>
<td>258,884</td>
<td></td>
<td>12,090,790</td>
<td></td>
<td>510,613</td>
<td>529</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>703,876,819</td>
<td>+587</td>
<td>7,003,621</td>
<td>+1</td>
<td>674,798,768</td>
<td>+1,967</td>
<td>22,074,430</td>
<td>35,470</td>
<td>90,301</td>
<td>898.5</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">111,558,488</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,216,367                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">109,308,801</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,033,320</td>
<td style="font-weight: bold; text-align:right">1,550</td>
<td style="font-weight: bold; text-align:right">333,204</td>
<td style="font-weight: bold; text-align:right">3,633</td>
<td style="font-weight: bold; text-align:right">1,186,765,074</td>
<td style="font-weight: bold; text-align:right">3,544,643</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>275</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3,086</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">45,030,332</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+120</td>
<td style="font-weight: bold; text-align:right;">533,496                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+1</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">32,013</td>
<td style="font-weight: bold; text-align:right">379</td>
<td style="font-weight: bold; text-align:right">935,879,495</td>
<td style="font-weight: bold; text-align:right">665,334</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,637</td><td>2</td>
<td style="font-weight: bold; text-align:right">0.09</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">0.8</td>
</tr>
<tr style="background-color:#F0F0F0">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">40,138,560</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">167,642                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,970,918</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">612,013</td>
<td style="font-weight: bold; text-align:right">2,556</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>391</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">38,822,474</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">182,649                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">38,240,600</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">399,225</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">462,814</td>
<td style="font-weight: bold; text-align:right">2,177</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>459</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">4,759</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">38,452,504</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">709,963                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,249,161</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,493,380</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">178,555</td>
<td style="font-weight: bold; text-align:right">3,297</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>303</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">6,935</td>
</tr>
<tr style="background-color:#F0F0F0">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">34,571,873</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">35,934                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">34,535,939</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">673,523</td>
<td style="font-weight: bold; text-align:right">700</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>1</td><td>1,428</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">33,803,572</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">74,694                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">269,169</td>
<td style="font-weight: bold; text-align:right">595</td>
<td style="font-weight: bold; text-align:right">100,414,883</td>
<td style="font-weight: bold; text-align:right">799,578</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>1,681</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">95,582</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">26,719,511</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">196,348                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">26,351,971</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">171,192</td>
<td style="font-weight: bold; text-align:right">45</td>
<td style="font-weight: bold; text-align:right">443,383</td>
<td style="font-weight: bold; text-align:right">3,258</td>
<td style="font-weight: bold; text-align:right">280,517,410</td>
<td style="font-weight: bold; text-align:right">4,654,904</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>307</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,841</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,902,971</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">232,112                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,666,932</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">3,927</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">363,558</td>
<td style="font-weight: bold; text-align:right">3,389</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>295</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">57</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">23,983,769</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">402,329                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">23,397,709</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">183,731</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">164,491</td>
<td style="font-weight: bold; text-align:right">2,759</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>362</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,260</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>

In [193]:
tags = table_code.find_all("tr")
tags
#print(type(tags))
#tags[-1].text

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">TotÂ Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>131,612,000</td>
 <td></td>
 <td>1,692,250</td>
 <td></td>
 <td>127,135,297</td>
 <td>+665</td>
 <td>2,784,453</td>
 <td>6,705</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>221,467,169</td>
 <td>+120</td>
 <td>1,553,255</td>
 <td>+1</td>
 <td>205,658,939</td>
 <td>+398</td>
 <td>14,254,975</td>
 <td>14,733</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>253,232,601</td>
 <td>+26</td>
 <td>2,100,643</td>
 <td></td>
 <td>248,565,603</td>
 <td>+904</td>
 <td>2,566,355</td>
 <td>4,510</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>69,859,756</td>
 <td></td>
 <td>1,365,807</td>
 <td></td>
 <td>66,650,237</td>
 <td></td>
 <td>1,843,712</td>
 <td>8,953</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>14,844,285</td>
 <td>+441</td>
 <td>32,767</td>
 <td></td>
 <td>14,697,196</td>
 <td></td>
 <td>114,322</td>
 <td>40</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,860,287</td>
 <td></td>
 <td>258,884</td>
 <td></td>
 <td>12,090,790</td>
 <td></td>
 <td>510,613</td>
 <td>529</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>703,876,819</td>
 <td>+587</td>
 <td>7,003,621</td>
 <td>+1</td>
 <td>674,798,768</td>
 <td>+1,967</td>
 <td>22,074,430</td>
 <td>35,470</td>
 <td>90,301</td>
 <td>898.5</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">111,558,488</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,216,367                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">109,308,801</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,033,320</td>
 <td style="font-weight: bold; text-align:right">1,550</td>
 <td style="font-weight: bold; text-align:right">333,204</td>
 <td style="font-weight: bold; text-align:right">3,633</td>
 <td style="font-weight: bold; text-align:right">1,186,765,074</td>
 <td style="font-weight: bold; text-align:right">3,544,643</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>275</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,086</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">45,030,332</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+120</td>
 <td style="font-weight: bold; text-align:right;">533,496                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+1</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">32,013</td>
 <td style="font-weight: bold; text-align:right">379</td>
 <td style="font-weight: bold; text-align:right">935,879,495</td>
 <td style="font-weight: bold; text-align:right">665,334</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,637</td><td>2</td>
 <td style="font-weight: bold; text-align:right">0.09</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">0.8</td>
 </tr>,
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">40,138,560</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">167,642                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,970,918</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">612,013</td>
 <td style="font-weight: bold; text-align:right">2,556</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>391</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">38,822,474</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">182,649                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">38,240,600</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">399,225</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">462,814</td>
 <td style="font-weight: bold; text-align:right">2,177</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>459</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">4,759</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">38,452,504</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">709,963                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,249,161</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,493,380</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">178,555</td>
 <td style="font-weight: bold; text-align:right">3,297</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>303</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">6,935</td>
 </tr>,
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">34,571,873</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">35,934                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">34,535,939</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">673,523</td>
 <td style="font-weight: bold; text-align:right">700</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>1</td><td>1,428</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">33,803,572</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">74,694                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">269,169</td>
 <td style="font-weight: bold; text-align:right">595</td>
 <td style="font-weight: bold; text-align:right">100,414,883</td>
 <td style="font-weight: bold; text-align:right">799,578</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>1,681</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">95,582</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">26,719,511</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">196,348                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">26,351,971</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">171,192</td>
 <td style="font-weight: bold; text-align:right">45</td>
 <td style="font-weight: bold; text-align:right">443,383</td>
 <td style="font-weight: bold; text-align:right">3,258</td>
 <td style="font-weight: bold; text-align:right">280,517,410</td>
 <td style="font-weight: bold; text-align:right">4,654,904</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>307</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,841</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,902,971</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">232,112                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,666,932</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">3,927</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">363,558</td>
 <td style="font-weight: bold; text-align:right">3,389</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>295</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">57</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">23,983,769</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">402,329                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">23,397,709</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">183,731</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">164,491</td>
 <td style="font-weight: bold; text-align:right">2,759</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,875,095</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>362</td><td>1</td>

In [203]:
data = []
for i in tags:
    y = i.text.split("\n")[1:]
    if y[0] != "":
        data.append(y)

data

[['#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot\xa0Cases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  '',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
  'New Cases/1M pop',
  'New Deaths/1M pop',
  'Active Cases/1M pop',
  ''],
 ['1',
  'USA',
  '111,558,488',
  '',
  '1,216,367                                ',
  '',
  '109,308,801',
  '',
  '1,033,320',
  '1,550',
  '333,204',
  '3,633',
  '1,186,765,074',
  '3,544,643',
  '334,805,269 ',
  'North America',
  '',
  '32750',
  '',
  '',
  '3,086',
  ''],
 ['2',
  'India',
  '45,030,332',
  '+120',
  '533,496                                ',
  '+1',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '32,013',
  '379',
  '935,879,495',
  '665,334',
  '1,406,631,776 ',
  'Asia',
  '',
  '312,6372',
  '0.09',
  '',
  '0.8',
  ''],
 ['3',
  'France',
  '40,138,560',
  '',
  '167,642                                ',
  '',
  '39,970,918',
  '',
  '0',
  '',
  '612,013',
  '2,556',
  '271,490,188',
  '4,139,547',
  '65,584,518 ',
  'Europe',
  '',
  '23910',
  '',
  '',
  '',
  ''],
 ['4',
  'Germany',
  '38,822,474',
  '',
  '182,649                                ',
  '',
  '38,240,600',
  '',
  '399,225',
  'N/A',
  '462,814',
  '2,177',
  '122,332,384',
  '1,458,359',
  '83,883,596 ',
  'Europe',
  '',
  '24591',
  '',
  '',
  '4,759',
  ''],
 ['5',
  'Brazil',
  '38,452,504',
  '',
  '709,963                                ',
  '',
  '36,249,161',
  '',
  '1,493,380',
  'N/A',
  '178,555',
  '3,297',
  '63,776,166',
  '296,146',
  '215,353,593 ',
  'South America',
  '',
  '63033',
  '',
  '',
  '6,935',
  ''],
 ['6',
  'S. Korea',
  '34,571,873',
  '',
  '35,934                                ',
  '',
  '34,535,939',
  '',
  '0',
  '',
  '673,523',
  '700',
  '15,804,065',
  '307,892',
  '51,329,899 ',
  'Asia',
  '',
  '11,4283',
  '',
  '',
  '',
  ''],
 ['7',
  'Japan',
  '33,803,572',
  '',
  '74,694                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '269,169',
  '595',
  '100,414,883',
  '799,578',
  '125,584,838 ',
  'Asia',
  '',
  '41,6811',
  '',
  '',
  '95,582',
  ''],
 ['8',
  'Italy',
  '26,719,511',
  '',
  '196,348                                ',
  '',
  '26,351,971',
  '',
  '171,192',
  '45',
  '443,383',
  '3,258',
  '280,517,410',
  '4,654,904',
  '60,262,770 ',
  'Europe',
  '',
  '23070',
  '',
  '',
  '2,841',
  ''],
 ['9',
  'UK',
  '24,902,971',
  '',
  '232,112                                ',
  '',
  '24,666,932',
  '',
  '3,927',
  'N/A',
  '363,558',
  '3,389',
  '522,526,476',
  '7,628,357',
  '68,497,907 ',
  'Europe',
  '',
  '32950',
  '',
  '',
  '57',
  ''],
 ['10',
  'Russia',
  '23,983,769',
  '',
  '402,329                                ',
  '',
  '23,397,709',
  '',
  '183,731',
  'N/A',
  '164,491',
  '2,759',
  '273,400,000',
  '1,875,095',
  '145,805,947 ',
  'Europe',
  '',
  '63621',
  '',
  '',
  '1,260',
  ''],
 ['11',
  'Turkey',
  '17,232,066',
  '',
  '102,174                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '201,399',
  '1,194',
  '162,743,369',
  '1,902,052',
  '85,561,976 ',
  'Asia',
  '',
  '58371',
  '',
  '',
  '4,024',
  ''],
 ['12',
  'Spain',
  '13,914,811',
  '',
  '121,760                                ',
  '',
  '13,762,417',
  '',
  '30,634',
  '231',
  '297,840',
  '2,606',
  '471,036,328',
  '10,082,298',
  '46,719,142 ',
  'Europe',
  '',
  '33840',
  '',
  '',
  '656',
  ''],
 ['13',
  'Australia',
  '11,824,150',
  '+441',
  '24,289                                ',
  '',
  '11,789,903',
  '',
  '9,958',
  '12',
  '453,575',
  '932',
  '81,916,639',
  '3,142,326',
  '26,068,792 ',
  'Australia/Oceania',
  '',
  '21,0730',
  '17',
  '',
  '382',
  ''],
 ['14',
  'Vietnam',
  '11,625,195',
  '',
  '43,206                                ',
  '',
  '10,640,971',
  '',
  '941,018',
  '',
  '117,481',
  '437',
  '85,826,548',
  '867,342',
  '98,953,541 ',
  'Asia',
  '',
  '92,2901',
  '',
  '',
  '9,510',
  ''],
 ['15',
  'Taiwan',
  '10,241,523',
  '',
  '19,005                                ',
  '',
  '10,222,518',
  '',
  '0',
  '',
  '428,720',
  '796',
  '30,742,304',
  '1,286,903',
  '23,888,595 ',
  'Asia',
  '',
  '21,2571',
  '',
  '',
  '',
  ''],
 ['16',
  'Argentina',
  '10,094,643',
  '',
  '130,733                                ',
  '',
  '9,963,910',
  '',
  '0',
  '',
  '219,400',
  '2,841',
  '35,716,069',
  '776,264',
  '46,010,234 ',
  'South America',
  '',
  '53521',
  '',
  '',
  '',
  ''],
 ['17',
  'Netherlands',
  '8,634,822',
  '',
  '22,992                                ',
  '',
  '8,610,982',
  '',
  '848',
  'N/A',
  '501,691',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447 ',
  'Europe',
  '',
  '27491',
  '',
  '',
  '49',
  ''],
 ['18',
  'Mexico',
  '7,702,809',
  '',
  '334,958                                ',
  '',
  '6,899,865',
  '',
  '467,986',
  'N/A',
  '58,549',
  '2,546',
  '20,013,810',
  '152,124',
  '131,562,772 ',
  'North America',
  '',
  '173937',
  '',
  '',
  '3,557',
  ''],
 ['19',
  'Iran',
  '7,626,527',
  '',
  '146,799                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '88,657',
  '1,707',
  '57,320,267',
  '666,338',
  '86,022,837 ',
  'Asia',
  '',
  '115862',
  '',
  '',
  '1,191',
  ''],
 ['20',
  'Indonesia',
  '6,829,005',
  '',
  '162,062                                ',
  '',
  '6,647,104',
  '',
  '19,839',
  'N/A',
  '24,465',
  '581',
  '114,158,919',
  '408,975',
  '279,134,505 ',
  'Asia',
  '',
  '411,7222',
  '',
  '',
  '71',
  ''],
 ['21',
  'Poland',
  '6,660,562',
  '+5',
  '120,573                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '176,486',
  '3,195',
  '39,284,243',
  '1,040,924',
  '37,739,785 ',
  'Europe',
  '',
  '63131',
  '0.1',
  '',
  '31,904',
  ''],
 ['22',
  'Colombia',
  '6,400,173',
  '',
  '143,200                                ',
  '',
  '6,212,152',
  '',
  '44,821',
  '342',
  '124,244',
  '2,780',
  '36,951,507',
  '717,327',
  '51,512,762 ',
  'South America',
  '',
  '83601',
  '',
  '',
  '870',
  ''],
 ['23',
  'Greece',
  '6,101,379',
  '',
  '37,869                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '591,412',
  '3,671',
  '102,228,365',
  '9,909,078',
  '10,316,637 ',
  'Europe',
  '',
  '22720',
  '',
  '',
  '',
  ''],
 ['24',
  'Austria',
  '6,081,287',
  '',
  '22,542                                ',
  '',
  '6,054,934',
  '',
  '3,811',
  '',
  '670,727',
  '2,486',
  '211,273,524',
  '23,302,116',
  '9,066,710 ',
  'Europe',
  '',
  '14020',
  '',
  '',
  '420',
  ''],
 ['25',
  'Portugal',
  '5,642,449',
  '',
  '28,103                                ',
  '',
  '5,614,102',
  '+270',
  '244',
  '61',
  '556,423',
  '2,771',
  '46,139,518',
  '4,549,993',
  '10,140,570 ',
  'Europe',
  '',
  '23610',
  '',
  '',
  '24',
  ''],
 ['26',
  'Ukraine',
  '5,557,995',
  '',
  '112,418                                ',
  '',
  '5,445,577',
  '',
  '0',
  '',
  '128,681',
  '2,603',
  '32,603,805',
  '754,855',
  '43,192,122 ',
  'Europe',
  '',
  '83841',
  '',
  '',
  '',
  ''],
 ['27',
  'Chile',
  '5,369,761',
  '',
  '64,497                                ',
  '',
  '5,252,450',
  '',
  '52,814',
  '7',
  '278,946',
  '3,350',
  '50,382,097',
  '2,617,225',
  '19,250,195 ',
  'South America',
  '',
  '42980',
  '',
  '',
  '2,744',
  ''],
 ['28',
  'Malaysia',
  '5,276,312',
  '',
  '37,348                                ',
  '',
  '5,230,953',
  '',
  '8,011',
  '11',
  '159,016',
  '1,126',
  '68,580,916',
  '2,066,869',
  '33,181,072 ',
  'Asia',
  '',
  '68880',
  '',
  '',
  '241',
  ''],
 ['29',
  'Canada',
  '4,933,311',
  '',
  '58,475                                ',
  '',
  '4,861,494',
  '+665',
  '13,342',
  '99',
  '128,510',
  '1,523',
  '66,572,774',
  '1,734,189',
  '38,388,419 ',
  'North America',
  '',
  '86561',
  '',
  '',
  '348',
  ''],
 ['30',
  'Belgium',
  '4,859,804',
  '',
  '34,376                                ',
  '',
  '4,822,825',
  '+194',
  '2,603',
  'N/A',
  '416,497',
  '2,946',
  '37,454,182',
  '3,209,915',
  '11,668,278 ',
  'Europe',
  '',
  '23390',
  '',
  '',
  '223',
  ''],
 ['31',
  'Israel',
  '4,841,772',
  '',
  '12,707                                ',
  '',
  '4,798,473',
  '',
  '30,592',
  'N/A',
  '519,169',
  '1,363',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '',
  '27340',
  '',
  '',
  '3,280',
  ''],
 ['32',
  'DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  '',
  '183,636',
  '3',
  '',
  '',
  '25,990,679 ',
  'Asia',
  '',
  '5351,225',
  '',
  '',
  '',
  ''],
 ['33',
  'Thailand',
  '4,767,238',
  '',
  '34,567                                ',
  '',
  '4,692,636',
  '',
  '40,035',
  'N/A',
  '68,027',
  '493',
  '17,273,454',
  '246,488',
  '70,078,203 ',
  'Asia',
  '',
  '152,0274',
  '',
  '',
  '571',
  ''],
 ['34',
  'Czechia',
  '4,758,599',
  '+1',
  '43,508                                ',
  '',
  '4,714,365',
  '+169',
  '726',
  '2',
  '443,205',
  '4,052',
  '57,803,906',
  '5,383,726',
  '10,736,784 ',
  'Europe',
  '',
  '22470',
  '0.09',
  '',
  '68',
  ''],
 ['35',
  'Peru',
  '4,572,667',
  '',
  '222,161                                ',
  '',
  '4,350,506',
  '',
  '0',
  '4',
  '135,751',
  '6,595',
  '39,010,194',
  '1,158,115',
  '33,684,208 ',
  'South America',
  '',
  '71521',
  '',
  '',
  '',
  ''],
 ['36',
  'Switzerland',
  '4,451,785',
  '',
  '14,452                                ',
  '',
  '4,436,453',
  '',
  '880',
  'N/A',
  '507,405',
  '1,647',
  '23,833,472',
  '2,716,487',
  '8,773,637 ',
  'Europe',
  '',
  '26070',
  '',
  '',
  '100',
  ''],
 ['37',
  'Philippines',
  '4,140,383',
  '',
  '66,864                                ',
  '',
  '4,067,381',
  '',
  '6,138',
  'N/A',
  '36,800',
  '594',
  '36,102,746',
  '320,888',
  '112,508,994 ',
  'Asia',
  '',
  '271,6833',
  '',
  '',
  '55',
  ''],
 ['38',
  'South Africa',
  '4,076,463',
  '',
  '102,595                                ',
  '',
  '3,912,506',
  '',
  '61,362',
  '192',
  '67,095',
  '1,689',
  '26,795,090',
  '441,027',
  '60,756,135 ',
  'Africa',
  '',
  '155922',
  '',
  '',
  '1,010',
  ''],
 ['39',
  'Romania',
  '3,527,050',
  '',
  '68,894                                ',
  '',
  '3,456,088',
  '',
  '2,068',
  '41',
  '185,329',
  '3,620',
  '28,660,306',
  '1,505,954',
  '19,031,335 ',
  'Europe',
  '',
  '52761',
  '',
  '',
  '109',
  ''],
 ['40',
  'Denmark',
  '3,183,756',
  '',
  '8,814                                ',
  '',
  '3,174,942',
  '',
  '0',
  '',
  '545,636',
  '1,511',
  '129,333,107',
  '22,165,247',
  '5,834,950 ',
  'Europe',
  '',
  '26620',
  '',
  '',
  '',
  ''],
 ['41',
  'Singapore',
  '3,006,155',
  '',
  '2,024                                ',
  '',
  '3,002,601',
  '+306',
  '1,530',
  '4',
  '505,785',
  '341',
  '24,756,666',
  '4,165,302',
  '5,943,546 ',
  'Asia',
  '',
  '22,9370',
  '',
  '',
  '257',
  ''],
 ['42',
  'Hong Kong',
  '2,930,929',
  '',
  '14,640                                ',
  '',
  '2,912,233',
  '',
  '4,056',
  'N/A',
  '385,431',
  '1,925',
  '76,127,725',
  '10,011,143',
  '7,604,299 ',
  'Asia',
  '',
  '35190',
  '',
  '',
  '533',
  ''],
 ['43',
  'Sweden',
  '2,753,556',
  '',
  '27,354                                ',
  '',
  '2,725,433',
  '+57',
  '769',
  'N/A',
  '269,455',
  '2,677',
  '19,500,873',
  '1,908,301',
  '10,218,971 ',
  'Europe',
  '',
  '43741',
  '',
  '',
  '75',
  ''],
 ['44',
  'Serbia',
  '2,614,248',
  '',
  '18,057                                ',
  '',
  '2,595,674',
  '',
  '517',
  '',
  '302,120',
  '2,087',
  '13,427,937',
  '1,551,822',
  '8,653,016 ',
  'Europe',
  '',
  '34791',
  '',
  '',
  '60',
  ''],
 ['45',
  'New Zealand',
  '2,598,630',
  '',
  '5,574                                ',
  '',
  '2,588,718',
  '',
  '4,338',
  '',
  '530,527',
  '1,138',
  '7,768,604',
  '1,586,011',
  '4,898,203 ',
  'Australia/Oceania',
  '',
  '28791',
  '',
  '',
  '886',
  ''],
 ['46',
  'Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497',
  '',
  '673',
  '',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965 ',
  'Asia',
  '',
  '171,6622',
  '',
  '',
  '16',
  ''],
 ['47',
  'Hungary',
  '2,229,987',
  '',
  '49,040                                ',
  '',
  '2,152,155',
  '',
  '28,792',
  '',
  '232,139',
  '5,105',
  '11,394,556',
  '1,186,160',
  '9,606,259 ',
  'Europe',
  '',
  '41961',
  '',
  '',
  '2,997',
  ''],
 ['48',
  'Bangladesh',
  '2,048,186',
  '',
  '29,488                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '12,200',
  '176',
  '15,254,399',
  '90,862',
  '167,885,689 ',
  'Asia',
  '',
  '825,69311',
  '',
  '',
  '-175.64',
  ''],
 ['49',
  'Slovakia',
  '1,877,383',
  '',
  '21,221                                ',
  '',
  '1,856,162',
  '',
  '0',
  '23',
  '343,831',
  '3,886',
  '7,448,789',
  '1,364,199',
  '5,460,193 ',
  'Europe',
  '',
  '32571',
  '',
  '',
  '',
  ''],
 ['50',
  'Georgia',
  '1,855,289',
  '',
  '17,132                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '467,476',
  '4,317',
  '16,920,079',
  '4,263,340',
  '3,968,738 ',
  'Asia',
  '',
  '22320',
  '',
  '',
  '15,524',
  ''],
 ['51',
  'Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869 ',
  'Asia',
  '',
  '67291',
  '',
  '',
  '181',
  ''],
 ['52',
  'Ireland',
  '1,733,755',
  '',
  '9,481                                ',
  '',
  '1,723,629',
  '',
  '645',
  '19',
  '345,356',
  '1,889',
  '13,083,449',
  '2,606,161',
  '5,020,199 ',
  'Europe',
  '',
  '35300',
  '',
  '',
  '128',
  ''],
 ['53',
  'Pakistan',
  '1,581,936',
  '',
  '30,664                                ',
  '',
  '1,538,689',
  '',
  '12,583',
  '',
  '6,893',
  '134',
  '30,589,153',
  '133,292',
  '229,488,994 ',
  'Asia',
  '',
  '1457,4848',
  '',
  '',
  '55',
  ''],
 ['54',
  'Finland',
  '1,515,575',
  '',
  '11,949                                ',
  '',
  '1,503,115',
  '+30',
  '511',
  'N/A',
  '272,833',
  '2,151',
  '12,108,977',
  '2,179,850',
  '5,554,960 ',
  'Europe',
  '',
  '44650',
  '',
  '',
  '92',
  ''],
 ['55',
  'Norway',
  '1,509,732',
  '',
  '6,638                                ',
  '',
  '1,503,024',
  '',
  '70',
  'N/A',
  '273,930',
  '1,204',
  '11,002,430',
  '1,996,315',
  '5,511,370 ',
  'Europe',
  '',
  '48301',
  '',
  '',
  '13',
  ''],
 ['56',
  'Kazakhstan',
  '1,411,831',
  '',
  '13,848                                ',
  '',
  '1,383,020',
  '',
  '14,963',
  '24',
  '73,514',
  '721',
  '11,575,012',
  '602,707',
  '19,205,043 ',
  'Asia',
  '',
  '141,3872',
  '',
  '',
  '779',
  ''],
 ['57',
  'Lithuania',
  '1,396,666',
  '+8',
  '9,897                                ',
  '',
  '1,385,651',
  '+168',
  '1,118',
  'N/A',
  '524,725',
  '3,718',
  '10,540,357',
  '3,959,997',
  '2,661,708 ',
  'Europe',
  '',
  '22690',
  '3',
  '',
  '420',
  ''],
 ['58',
  'Slovenia',
  '1,356,454',
  '+2',
  '7,100                                ',
  '',
  '1,349,283',
  '+16',
  '71',
  'N/A',
  '652,758',
  '3,417',
  '2,847,701',
  '1,370,382',
  '2,078,034 ',
  'Europe',
  '',
  '22931',
  '1.0',
  '',
  '34',
  ''],
 ['59',
  'Bulgaria',
  '1,339,501',
  '+10',
  '38,737                                ',
  '',
  '1,292,640',
  '',
  '8,124',
  '36',
  '195,702',
  '5,660',
  '11,636,936',
  '1,700,164',
  '6,844,597 ',
  'Europe',
  '',
  '51771',
  '1',
  '',
  '1,187',
  ''],
 ['60',
  'Croatia',
  '1,309,728',
  '',
  '18,687                                ',
  '',
  '1,258,432',
  '',
  '32,609',
  '',
  '322,650',
  '4,604',
  '5,660,084',
  '1,394,355',
  '4,059,286 ',
  'Europe',
  '',
  '32171',
  '',
  '',
  '8,033',
  ''],
 ['61',
  'Guatemala',
  '1,288,588',
  '',
  '20,285                                ',
  '',
  '1,265,533',
  '',
  '2,770',
  '5',
  '69,338',
  '1,092',
  '7,593,848',
  '408,622',
  '18,584,039 ',
  'North America',
  '',
  '149162',
  '',
  '',
  '149',
  ''],
 ['62',
  'Morocco',
  '1,278,944',
  '',
  '16,301                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '33,859',
  '432',
  '13,001,033',
  '344,191',
  '37,772,756 ',
  'Africa',
  '',
  '302,3173',
  '',
  '',
  '172',
  ''],
 ['63',
  'Lebanon',
  '1,243,838',
  '',
  '10,952                                ',
  '',
  '1,087,587',
  '',
  '145,299',
  '74',
  '186,068',
  '1,638',
  '4,795,578',
  '717,380',
  '6,684,849 ',
  'Asia',
  '',
  '56101',
  '',
  '',
  '21,736',
  ''],
 ['64',
  'Costa Rica',
  '1,238,883',
  '',
  '9,428                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '239,058',
  '1,819',
  '4,659,757',
  '899,158',
  '5,182,354 ',
  'North America',
  '',
  '45501',
  '',
  '',
  '71,154',
  ''],
 ['65',
  'Bolivia',
  '1,211,716',
  '',
  '22,407                                ',
  '',
  '1,177,145',
  '',
  '12,164',
  '220',
  '101,038',
  '1,868',
  '2,710,261',
  '225,993',
  '11,992,656 ',
  'South America',
  '',
  '105354',
  '',
  '',
  '1,014',
  ''],
 ['66',
  'Tunisia',
  '1,153,361',
  '',
  '29,423                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '95,741',
  '2,442',
  '5,013,383',
  '416,164',
  '12,046,656 ',
  'Africa',
  '',
  '104092',
  '',
  '',
  '1,157',
  ''],
 ['67',
  'Cuba',
  '1,115,243',
  '',
  '8,530                                ',
  '',
  '1,106,647',
  '',
  '66',
  '',
  '98,645',
  '754',
  '14,401,151',
  '1,273,801',
  '11,305,652 ',
  'North America',
  '',
  '101,3251',
  '',
  '',
  '6',
  ''],
 ['68',
  'Ecuador',
  '1,070,188',
  '',
  '36,043                                ',
  '',
  '1,034,145',
  '',
  '0',
  '',
  '59,083',
  '1,990',
  '3,082,403',
  '170,173',
  '18,113,361 ',
  'South America',
  '',
  '175036',
  '',
  '',
  '',
  ''],
 ['69',
  'UAE',
  '1,067,030',
  '',
  '2,349                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '105,837',
  '233',
  '200,732,262',
  '19,910,389',
  '10,081,785 ',
  'Asia',
  '',
  '94,2920',
  '',
  '',
  '1,007',
  ''],
 ['70',
  'Panama',
  '1,059,893',
  '',
  '8,727                                ',
  '',
  '1,051,102',
  '',
  '64',
  '16',
  '238,341',
  '1,962',
  '7,882,622',
  '1,772,585',
  '4,446,964 ',
  'North America',
  '',
  '45101',
  '',
  '',
  '14',
  ''],
 ['71',
  'Uruguay',
  '1,041,111',
  '',
  '7,664                                ',
  '',
  '1,030,944',
  '',
  '2,503',
  '18',
  '297,799',
  '2,192',
  '6,114,822',
  '1,749,083',
  '3,496,016 ',
  'South America',
  '',
  '34561',
  '',
  '',
  '716',
  ''],
 ['72',
  'Mongolia',
  '1,011,459',
  '',
  '2,284                                ',
  '',
  '1,009,175',
  '',
  '0',
  'N/A',
  '299,418',
  '676',
  '4,030,048',
  '1,193,000',
  '3,378,078 ',
  'Asia',
  '',
  '31,4791',
  '',
  '',
  '',
  ''],
 ['73',
  'Nepal',
  '1,003,450',
  '',
  '12,031                                ',
  '',
  '991,322',
  '',
  '97',
  '',
  '33,199',
  '398',
  '6,047,766',
  '200,088',
  '30,225,582 ',
  'Asia',
  '',
  '302,5125',
  '',
  '',
  '3',
  ''],
 ['74',
  'Belarus',
  '994,037',
  '',
  '7,118                                ',
  '',
  '985,592',
  '',
  '1,327',
  '',
  '105,381',
  '755',
  '13,646,641',
  '1,446,722',
  '9,432,800 ',
  'Europe',
  '',
  '91,3251',
  '',
  '',
  '141',
  ''],
 ['75',
  'Latvia',
  '982,280',
  '',
  '6,686                                ',
  '',
  '971,406',
  '',
  '4,188',
  '',
  '531,296',
  '3,616',
  '7,885,792',
  '4,265,272',
  '1,848,837 ',
  'Europe',
  '',
  '22770',
  '',
  '',
  '2,265',
  ''],
 ['76',
  'Saudi Arabia',
  '841,469',

In [195]:
type(data[0])

list

In [196]:
data[0]

['#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot\xa0Cases/1M pop',
 'Deaths/1M pop',
 'TotalTests',
 'Tests/',
 '1M pop',
 '',
 'Population',
 'Continent',
 '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
 'New Cases/1M pop',
 'New Deaths/1M pop',
 'Active Cases/1M pop',
 '']

In [65]:
import csv
import pandas as pd

file = open("covid.csv","w")
x = csv.writer(file)
x.writerows(data)
file.close()

In [66]:
df = pd.read_csv("covid.csv",encoding = "latin1")
df.head(10)

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop,Unnamed: 22
0,1,USA,"111,558,488",NaN,"1,216,367",NaN,"109,308,801",NaN,"1,033,320","1,550",...,"3,544,643","334,805,269",North America,NaN,32750,NaN,NaN,"3,086",NaN,NaN
1,2,India,"45,030,212",NaN,"533,495",NaN,NaN,NaN,NaN,NaN,...,"665,334","1,406,631,776",Asia,NaN,"312,6372",NaN,NaN,0.8,NaN,NaN
2,3,France,"40,138,560",NaN,"167,642",NaN,"39,970,918",NaN,0,NaN,...,"4,139,547","65,584,518",Europe,NaN,23910,NaN,NaN,NaN,NaN,NaN
3,4,Germany,"38,822,474",NaN,"182,649",NaN,"38,240,600",NaN,"399,225",NaN,...,"1,458,359","83,883,596",Europe,NaN,24591,NaN,NaN,"4,759",NaN,NaN
4,5,Brazil,"38,452,504",NaN,"709,963",NaN,"36,249,161",NaN,"1,493,380",NaN,...,"296,146","215,353,593",South America,NaN,63033,NaN,NaN,"6,935",NaN,NaN
5,6,S. Korea,"34,571,873",NaN,"35,934",NaN,"34,535,939",NaN,0,NaN,...,"307,892","51,329,899",Asia,NaN,"11,4283",NaN,NaN,NaN,NaN,NaN
6,7,Japan,"33,803,572",NaN,"74,694",NaN,NaN,NaN,NaN,NaN,...,"799,578","125,584,838",Asia,NaN,"41,6811",NaN,NaN,"95,582",NaN,NaN
7,8,Italy,"26,719,511",NaN,"196,348",NaN,"26,351,971",NaN,"171,192",45,...,"4,654,904","60,262,770",Europe,NaN,23070,NaN,NaN,"2,841",NaN,NaN
8,9,UK,"24,902,971",NaN,"232,112",NaN,"24,666,932",NaN,"3,927",NaN,...,"7,628,357","68,497,907",Europe,NaN,32950,NaN,NaN,57,NaN,NaN
9,10,Russia,"23,983,769",NaN,"402,329",NaN,"23,397,709",NaN,"183,731",NaN,...,"1,875,095","145,805,947",Europe,NaN,63621,NaN,NaN,"1,260",NaN,NaN

In [67]:
df.shape

(231, 23)

In [68]:
df.columns

Index(['#', 'Country,Other', 'TotalCases', 'NewCases', 'TotalDeaths',
       'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases',
       'Serious,Critical', 'TotÂ Cases/1M pop', 'Deaths/1M pop', 'TotalTests',
       'Tests/', '1M pop', 'Unnamed: 15', 'Population', 'Continent',
       '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
       'New Cases/1M pop', 'New Deaths/1M pop', 'Active Cases/1M pop',
       'Unnamed: 22'],
      dtype='object')

In [69]:
df.isnull().sum()

#                                                         0
Country,Other                                             0
TotalCases                                                0
NewCases                                                227
TotalDeaths                                               0
NewDeaths                                               231
TotalRecovered                                           48
NewRecovered                                            223
ActiveCases                                              47
Serious,Critical                                        179
TotÂ Cases/1M pop                                          2
Deaths/1M pop                                             7
TotalTests                                               18
Tests/                                                   18
1M pop                                                    0
Unnamed: 15                                               2
Population                                              231
Continent                                                 2
1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl    227
New Cases/1M pop                                        231
New Deaths/1M pop                                        26
Active Cases/1M pop                                     231
Unnamed: 22                                             231
dtype: int64

In [70]:
df.describe()

,#,NewCases,NewDeaths,NewRecovered,Population,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,Active Cases/1M pop,Unnamed: 22
count,231.000000,4.00000,0.0,8.000000,0.0,4.00000,0.0,0.0,0.0
mean,116.000000,115.25000,NaN,213.250000,NaN,5.50000,NaN,NaN,NaN
std,66.828138,217.19327,NaN,212.206604,NaN,7.72442,NaN,NaN,NaN
min,1.000000,2.00000,NaN,16.000000,NaN,1.00000,NaN,NaN,NaN
25%,58.500000,6.50000,NaN,50.250000,NaN,1.00000,NaN,NaN,NaN
50%,116.000000,9.00000,NaN,181.000000,NaN,2.00000,NaN,NaN,NaN
75%,173.500000,117.75000,NaN,279.000000,NaN,6.50000,NaN,NaN,NaN
max,231.000000,441.00000,NaN,665.000000,NaN,17.00000,NaN,NaN,NaN

In [71]:
#plotting top 10 countries data
x = df["Country,Other"][:10]
y = df["TotalCases"][:10]

0    111,558,488
1     45,030,212
2     40,138,560
3     38,822,474
4     38,452,504
5     34,571,873
6     33,803,572
7     26,719,511
8     24,902,971
9     23,983,769
Name: TotalCases, dtype: object

In [72]:
y = [int(i.replace(",","")) for i in y]
df["TotalCases"][:10] = y
df

C:\Users\Acer\AppData\Local\Temp\ipykernel_12276\2813676585.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop,Unnamed: 22
0,1,USA,111558488,NaN,"1,216,367",NaN,"109,308,801",NaN,"1,033,320","1,550",...,"3,544,643","334,805,269",North America,NaN,32750,NaN,NaN,"3,086",NaN,NaN
1,2,India,45030212,NaN,"533,495",NaN,NaN,NaN,NaN,NaN,...,"665,334","1,406,631,776",Asia,NaN,"312,6372",NaN,NaN,0.8,NaN,NaN
2,3,France,40138560,NaN,"167,642",NaN,"39,970,918",NaN,0,NaN,...,"4,139,547","65,584,518",Europe,NaN,23910,NaN,NaN,NaN,NaN,NaN
3,4,Germany,38822474,NaN,"182,649",NaN,"38,240,600",NaN,"399,225",NaN,...,"1,458,359","83,883,596",Europe,NaN,24591,NaN,NaN,"4,759",NaN,NaN
4,5,Brazil,38452504,NaN,"709,963",NaN,"36,249,161",NaN,"1,493,380",NaN,...,"296,146","215,353,593",South America,NaN,63033,NaN,NaN,"6,935",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,227,Tokelau,80,NaN,,NaN,NaN,NaN,80,NaN,...,NaN,"1,378",Australia/Oceania,NaN,17,NaN,NaN,"58,055",NaN,NaN
227,228,Vatican City,29,NaN,,NaN,29,NaN,0,NaN,...,NaN,799,Europe,NaN,28,NaN,NaN,NaN,NaN,NaN
228,229,Western Sahara,10,NaN,1,NaN,9,NaN,0,NaN,...,NaN,"626,161",Africa,NaN,"62,616626,161",NaN,NaN,NaN,NaN,NaN
229,230,MS Zaandam,9,NaN,2,NaN,7,NaN,0,NaN,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,231,China,"503,302",NaN,"5,272",NaN,"379,053",NaN,"118,977",NaN,...,"110,461","1,448,471,400",Asia,NaN,"2,878274,7489",NaN,NaN,82,NaN,NaN

In [159]:
# !pip install plotly == 5.19.0

# TotalCases vs Country,Other

In [74]:
import plotly.express as px
fig = px.bar(df[:10], x='Country,Other', y='TotalCases')
fig.show()

In [75]:
y1 = df["TotalDeaths"][:10]
y1 = [int(i.replace(",","")) for i in y1]
df["TotalDeaths"][:10] = y1
df

C:\Users\Acer\AppData\Local\Temp\ipykernel_12276\2412333408.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop,Unnamed: 22
0,1,USA,111558488,NaN,1216367,NaN,"109,308,801",NaN,"1,033,320","1,550",...,"3,544,643","334,805,269",North America,NaN,32750,NaN,NaN,"3,086",NaN,NaN
1,2,India,45030212,NaN,533495,NaN,NaN,NaN,NaN,NaN,...,"665,334","1,406,631,776",Asia,NaN,"312,6372",NaN,NaN,0.8,NaN,NaN
2,3,France,40138560,NaN,167642,NaN,"39,970,918",NaN,0,NaN,...,"4,139,547","65,584,518",Europe,NaN,23910,NaN,NaN,NaN,NaN,NaN
3,4,Germany,38822474,NaN,182649,NaN,"38,240,600",NaN,"399,225",NaN,...,"1,458,359","83,883,596",Europe,NaN,24591,NaN,NaN,"4,759",NaN,NaN
4,5,Brazil,38452504,NaN,709963,NaN,"36,249,161",NaN,"1,493,380",NaN,...,"296,146","215,353,593",South America,NaN,63033,NaN,NaN,"6,935",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,227,Tokelau,80,NaN,,NaN,NaN,NaN,80,NaN,...,NaN,"1,378",Australia/Oceania,NaN,17,NaN,NaN,"58,055",NaN,NaN
227,228,Vatican City,29,NaN,,NaN,29,NaN,0,NaN,...,NaN,799,Europe,NaN,28,NaN,NaN,NaN,NaN,NaN
228,229,Western Sahara,10,NaN,1,NaN,9,NaN,0,NaN,...,NaN,"626,161",Africa,NaN,"62,616626,161",NaN,NaN,NaN,NaN,NaN
229,230,MS Zaandam,9,NaN,2,NaN,7,NaN,0,NaN,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,231,China,"503,302",NaN,"5,272",NaN,"379,053",NaN,"118,977",NaN,...,"110,461","1,448,471,400",Asia,NaN,"2,878274,7489",NaN,NaN,82,NaN,NaN

# TotalCases vs TotalDeaths

# Grouped Bar Chart

In [163]:
import plotly.graph_objects as go
#animals=['giraffes', 'orangutans', 'monkeys']

fig = go.Figure(data=[
    go.Bar(name='TotalCases', x=df["Country,Other"][:10], y=df["TotalCases"][:10]),
    go.Bar(name='TotalDeaths', x=df["Country,Other"][:10], y=df["TotalDeaths"][:10])
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.show()

# TotalCases vs TotalRecovered

In [157]:
y2 = df["TotalRecovered"][:10]
y2_list = []
for values in y2:
    if type(values) == type(str()):
        t = values.replace(',',"")
        y2_list.append(float(t))
    else:
        y2_list.append(values)

In [158]:
df["TotalRecovered"][:10] = y2_list
mean = df["TotalRecovered"][:10].mean()

df["TotalRecovered"][:10].fillna(mean,inplace=True)
df.head(10)

C:\Users\Acer\AppData\Local\Temp\ipykernel_12276\3721126152.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop,Unnamed: 22
0,1,USA,111558488,NaN,1216367,NaN,109308801.0,NaN,"1,033,320","1,550",...,"3,544,643","334,805,269",North America,NaN,32750,NaN,NaN,"3,086",NaN,NaN
1,2,India,45030212,NaN,533495,NaN,41590253.875,NaN,NaN,NaN,...,"665,334","1,406,631,776",Asia,NaN,"312,6372",NaN,NaN,0.8,NaN,NaN
2,3,France,40138560,NaN,167642,NaN,39970918.0,NaN,0,NaN,...,"4,139,547","65,584,518",Europe,NaN,23910,NaN,NaN,NaN,NaN,NaN
3,4,Germany,38822474,NaN,182649,NaN,38240600.0,NaN,"399,225",NaN,...,"1,458,359","83,883,596",Europe,NaN,24591,NaN,NaN,"4,759",NaN,NaN
4,5,Brazil,38452504,NaN,709963,NaN,36249161.0,NaN,"1,493,380",NaN,...,"296,146","215,353,593",South America,NaN,63033,NaN,NaN,"6,935",NaN,NaN
5,6,S. Korea,34571873,NaN,35934,NaN,34535939.0,NaN,0,NaN,...,"307,892","51,329,899",Asia,NaN,"11,4283",NaN,NaN,NaN,NaN,NaN
6,7,Japan,33803572,NaN,74694,NaN,41590253.875,NaN,NaN,NaN,...,"799,578","125,584,838",Asia,NaN,"41,6811",NaN,NaN,"95,582",NaN,NaN
7,8,Italy,26719511,NaN,196348,NaN,26351971.0,NaN,"171,192",45,...,"4,654,904","60,262,770",Europe,NaN,23070,NaN,NaN,"2,841",NaN,NaN
8,9,UK,24902971,NaN,232112,NaN,24666932.0,NaN,"3,927",NaN,...,"7,628,357","68,497,907",Europe,NaN,32950,NaN,NaN,57,NaN,NaN
9,10,Russia,23983769,NaN,402329,NaN,23397709.0,NaN,"183,731",NaN,...,"1,875,095","145,805,947",Europe,NaN,63621,NaN,NaN,"1,260",NaN,NaN

In [154]:
mean

41590253.875

# Stacked Bar Chart

In [162]:
import plotly.graph_objects as go
#animals=['giraffes', 'orangutans', 'monkeys']

fig = go.Figure(data=[
    go.Bar(name='TotalCases', x=df["Country,Other"][:10], y=df["TotalCases"][:10]),
    go.Bar(name='TotalDeaths', x=df["Country,Other"][:10], y=df["TotalRecovered"][:10])
])
# Change the bar mode
fig.update_layout(barmode='stack')
fig.show()

# TotalCases vs ActiveCases

In [164]:
y3 = df["ActiveCases"][:10]
y3_list = []
for values in y3:
    if type(values) == type(str()):
        t = values.replace(',',"")
        y3_list.append(float(t))
    else:
        y3_list.append(values)

In [165]:
df["ActiveCases"][:10] = y3_list
mean = df["ActiveCases"][:10].mean()

df["ActiveCases"][:10].fillna(mean,inplace=True)
df.head(10)

C:\Users\Acer\AppData\Local\Temp\ipykernel_12276\1390562264.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop,Unnamed: 22
0,1,USA,111558488,NaN,1216367,NaN,109308801.0,NaN,1033320.0,"1,550",...,"3,544,643","334,805,269",North America,NaN,32750,NaN,NaN,"3,086",NaN,NaN
1,2,India,45030212,NaN,533495,NaN,41590253.875,NaN,410596.875,NaN,...,"665,334","1,406,631,776",Asia,NaN,"312,6372",NaN,NaN,0.8,NaN,NaN
2,3,France,40138560,NaN,167642,NaN,39970918.0,NaN,0.0,NaN,...,"4,139,547","65,584,518",Europe,NaN,23910,NaN,NaN,NaN,NaN,NaN
3,4,Germany,38822474,NaN,182649,NaN,38240600.0,NaN,399225.0,NaN,...,"1,458,359","83,883,596",Europe,NaN,24591,NaN,NaN,"4,759",NaN,NaN
4,5,Brazil,38452504,NaN,709963,NaN,36249161.0,NaN,1493380.0,NaN,...,"296,146","215,353,593",South America,NaN,63033,NaN,NaN,"6,935",NaN,NaN
5,6,S. Korea,34571873,NaN,35934,NaN,34535939.0,NaN,0.0,NaN,...,"307,892","51,329,899",Asia,NaN,"11,4283",NaN,NaN,NaN,NaN,NaN
6,7,Japan,33803572,NaN,74694,NaN,41590253.875,NaN,410596.875,NaN,...,"799,578","125,584,838",Asia,NaN,"41,6811",NaN,NaN,"95,582",NaN,NaN
7,8,Italy,26719511,NaN,196348,NaN,26351971.0,NaN,171192.0,45,...,"4,654,904","60,262,770",Europe,NaN,23070,NaN,NaN,"2,841",NaN,NaN
8,9,UK,24902971,NaN,232112,NaN,24666932.0,NaN,3927.0,NaN,...,"7,628,357","68,497,907",Europe,NaN,32950,NaN,NaN,57,NaN,NaN
9,10,Russia,23983769,NaN,402329,NaN,23397709.0,NaN,183731.0,NaN,...,"1,875,095","145,805,947",Europe,NaN,63621,NaN,NaN,"1,260",NaN,NaN

In [166]:
mean

410596.875

# Donut Chart

In [170]:
import plotly.graph_objects as go

labels = df["Country,Other"][:10]
values = df["ActiveCases"]

# Use `hole` to create a donut-like pie chart
fig = go.Figure(data=[go.Pie(labels=labels, values=values, hole=.5)])
fig.show()

In [171]:
df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop,Unnamed: 22
0,1,USA,111558488,NaN,1216367,NaN,109308801.0,NaN,1033320.0,"1,550",...,"3,544,643","334,805,269",North America,NaN,32750,NaN,NaN,"3,086",NaN,NaN
1,2,India,45030212,NaN,533495,NaN,41590253.875,NaN,410596.875,NaN,...,"665,334","1,406,631,776",Asia,NaN,"312,6372",NaN,NaN,0.8,NaN,NaN
2,3,France,40138560,NaN,167642,NaN,39970918.0,NaN,0.0,NaN,...,"4,139,547","65,584,518",Europe,NaN,23910,NaN,NaN,NaN,NaN,NaN
3,4,Germany,38822474,NaN,182649,NaN,38240600.0,NaN,399225.0,NaN,...,"1,458,359","83,883,596",Europe,NaN,24591,NaN,NaN,"4,759",NaN,NaN
4,5,Brazil,38452504,NaN,709963,NaN,36249161.0,NaN,1493380.0,NaN,...,"296,146","215,353,593",South America,NaN,63033,NaN,NaN,"6,935",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,227,Tokelau,80,NaN,,NaN,NaN,NaN,80,NaN,...,NaN,"1,378",Australia/Oceania,NaN,17,NaN,NaN,"58,055",NaN,NaN
227,228,Vatican City,29,NaN,,NaN,29,NaN,0,NaN,...,NaN,799,Europe,NaN,28,NaN,NaN,NaN,NaN,NaN
228,229,Western Sahara,10,NaN,1,NaN,9,NaN,0,NaN,...,NaN,"626,161",Africa,NaN,"62,616626,161",NaN,NaN,NaN,NaN,NaN
229,230,MS Zaandam,9,NaN,2,NaN,7,NaN,0,NaN,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,231,China,"503,302",NaN,"5,272",NaN,"379,053",NaN,"118,977",NaN,...,"110,461","1,448,471,400",Asia,NaN,"2,878274,7489",NaN,NaN,82,NaN,NaN